"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var zooApp_js_1 = require("./zooApp.js");
var lion_js_1 = require("./zooLab/animals/mammal/lion.js");
var turtle_js_1 = require("./zooLab/animals/reptile/turtle.js");
var enclosure_js_1 = require("./zooLab/enclosure.js");
var zoo_js_1 = require("./zooLab/zoo.js");
var zooApp = new zooApp_js_1.ZooApp('zooApp1');
var zoo1 = new zoo_js_1.Zoo('location1');
var zoo2 = new zoo_js_1.Zoo('location2');
zooApp.AddZoo(zoo1);
zooApp.AddZoo(zoo2);
var enclosure1 = new enclosure_js_1.Enclosure('Lions', 4500);
var enclosure2 = new enclosure_js_1.Enclosure('Birds', 25);
zoo1.AddEnclosure(enclosure1);
zoo1.AddEnclosure(enclosure2);
var lion1 = new lion_js_1.Lion();
var lion2 = new lion_js_1.Lion();
var lion3 = new lion_js_1.Lion();
var lion4 = new lion_js_1.Lion();
var turtle1 = new turtle_js_1.Turtle();
zoo1.AddAnimal(lion1);
zoo1.AddAnimal(lion2);
zoo1.AddAnimal(lion3);
zoo1.AddAnimal(lion4);
zoo1.RemoveAnimal(lion1);
zoo1.AddAnimal(turtle1);
